# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
deck = Deck.create(name: "JLPT N5 Kanji")
sql = <<-SQL
INSERT INTO cards(deck_id, front, back)
VALUES
(#{deck.id}, '学', 'study/learning/science'),
(#{deck.id}, '中', 'in/inside/middle/mean/center'),
(#{deck.id}, '金', 'gold'),
(#{deck.id}, '人', 'person'),
(#{deck.id}, '一', 'one'),
(#{deck.id}, '入', 'enter/insert'),
(#{deck.id}, '万', 'ten thousand'),
(#{deck.id}, '後', 'behind/back/later'),
(#{deck.id}, '東', 'east'),
(#{deck.id}, '見', 'see/hopes/chances/idea/opinion/look at/visible'),
(#{deck.id}, '出', 'exit/leave'),
(#{deck.id}, '本', 'book/present/main/true/real/counter for long things'),
(#{deck.id}, '長', 'long/leader'),
(#{deck.id}, '十', 'ten'),
(#{deck.id}, '間', 'interval/space'),
(#{deck.id}, '水', 'water'),
(#{deck.id}, '食', 'eat/food'),
(#{deck.id}, '上', 'above/up'),
(#{deck.id}, '七', 'seven'),
(#{deck.id}, '何', 'what'),
(#{deck.id}, '校', 'exam/school/printing/proof/correction'),
(#{deck.id}, '白', 'white'),
(#{deck.id}, '四', 'four'),
(#{deck.id}, '右', 'right'),
(#{deck.id}, '左', 'left'),
(#{deck.id}, '前', 'in front/before'),
(#{deck.id}, '木', 'tree/wood'),
(#{deck.id}, '行', 'going/journey'),
(#{deck.id}, '二', 'two'),
(#{deck.id}, '生', 'life/genuine/birth'),
(#{deck.id}, '土', 'soil/earth/ground/Turkey'),
(#{deck.id}, '友', 'friend'),
(#{deck.id}, '南', 'south'),
(#{deck.id}, '車', 'car'),
(#{deck.id}, '先', 'before/ahead/previous/future/precedence'),
(#{deck.id}, '三', 'three'),
(#{deck.id}, '天', 'heavens/sky/imperial'),
(#{deck.id}, '気', 'spirit/mind'),
(#{deck.id}, '高', 'tall/high/expensive'),
(#{deck.id}, '百', 'hundred'),
(#{deck.id}, '今', 'now'),
(#{deck.id}, '外', 'outside'),
(#{deck.id}, '火', 'fire'),
(#{deck.id}, '女', 'woman/female'),
(#{deck.id}, '読', 'read'),
(#{deck.id}, '午', 'noon/sign of the horse/11AM-1PM/seventh sign of Chinese zodiac'),
(#{deck.id}, '電', 'electricity'),
(#{deck.id}, '毎', 'every'),
(#{deck.id}, '休', 'rest/day off/retire/sleep'),
(#{deck.id}, '書', 'write'),
(#{deck.id}, '話', 'tale/talk'),
(#{deck.id}, '西', 'west/Spain'),
(#{deck.id}, '日', 'day/sun/Japan'),
(#{deck.id}, '円', 'circle/yen/round'),
(#{deck.id}, '国', 'country'),
(#{deck.id}, '八', 'eight'),
(#{deck.id}, '子', 'child/sign of the rat/11PM-1AM/first sign of Chinese zodiac'),
(#{deck.id}, '母', 'mama/mother'),
(#{deck.id}, '男', 'male'),
(#{deck.id}, '五', 'five'),
(#{deck.id}, '時', 'time/hour'),
(#{deck.id}, '六', 'six'),
(#{deck.id}, '月', 'month/moon'),
(#{deck.id}, '小', 'little/small'),
(#{deck.id}, '来', 'come/due/next/cause/become'),
(#{deck.id}, '大', 'large/big'),
(#{deck.id}, '半', 'half/middle/odd number/semi-/part-'),
(#{deck.id}, '雨', 'rain'),
(#{deck.id}, '千', 'thousand'),
(#{deck.id}, '年', 'year'),
(#{deck.id}, '川', 'stream/river'),
(#{deck.id}, '下', 'below/down/descend/give/low/inferior'),
(#{deck.id}, '聞', 'hear/ask/listen'),
(#{deck.id}, '語', 'word/speech/language'),
(#{deck.id}, '山', 'mountain'),
(#{deck.id}, '父', 'father'),
(#{deck.id}, '名', 'name/noted/distinguished/reputation'),
(#{deck.id}, '九', 'nine'),
(#{deck.id}, '北', 'north')
SQL

ActiveRecord::Base.connection.execute sql
